### PR TITLE
New Messages Fixes

### PR DESCRIPTION
**Pull request by abhiram555**
fixed some messages placeholders and add support to placeholder api

### CODE REVIEW

**Comment by regulad** [comment]
These placeholders arent handled by pAPI. All placeholders must be handled by pAPI.

**Review by regulad — CHANGES_REQUESTED** [review]
These placeholders aren't handled by pAPI, so they cannot be used out of messages displayed by this plugin. All placeholders must be handled with pAPI.

**Comment by regulad** [comment]
> 
> 
> These placeholders aren't handled by pAPI, so they cannot be used out of messages displayed by this plugin. All placeholders must be handled with pAPI.

also pretty sure they wont work with hex color codes, which is an issue

**Comment by abhiram555** [comment]
> These placeholders aren't handled by pAPI, so they cannot be used out of messages displayed by this plugin. All placeholders must be handled with pAPI.

???

**Comment by abhiram555** [comment]
> These placeholders aren't handled by pAPI, so they cannot be used out of messages displayed by this plugin. All placeholders must be handled with pAPI.

they support papi placeholders...., i don't know how to make the handled by papi

**Comment by regulad** [comment]
> 
> 
> > These placeholders aren't handled by pAPI, so they cannot be used out of messages displayed by this plugin. All placeholders must be handled with pAPI.
> 
> they support papi placeholders...., i don't know how to make the handled by papi

The plugin already has pAPI integrated. See the wiki: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI

**Comment by abhiram555** [comment]
> > > These placeholders aren't handled by pAPI, so they cannot be used out of messages displayed by this plugin. All placeholders must be handled with pAPI.
> > 
> > 
> > they support papi placeholders...., i don't know how to make the handled by papi
> 
> The plugin already has pAPI integrated. See the wiki: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI

well that's how to set placeholders and add placeholders i am asking what you mean by handle messages by papi like do you want me to add more placeholders?

**Comment by regulad** [comment]
> 
> 
> > > > These placeholders aren't handled by pAPI, so they cannot be used out of messages displayed by this plugin. All placeholders must be handled with pAPI.
> > > 
> > > 
> > > they support papi placeholders...., i don't know how to make the handled by papi
> > 
> > 
> > The plugin already has pAPI integrated. See the wiki: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI
> 
> well that's how to set placeholders and add placeholders i am asking what you mean by handle messages by papi like do you want me to add more placeholders?

Certain things like `%id%` and `%minutes%` are just aliases for papi placeholders, can you remove the aliases and allow me to just put in papi placeholders?

**Comment by regulad** [comment]
Covered by #13

**Pull request closed without merging**
